// Production-grade Submittal Package PDF.
//
// Bundles the project's BOM + Compliance + Regulatory Readiness + Cable
// Schedule into a multi-page Letter-sized PDF with cover sheet, RCDD/PE
// stamp box, and section headers. This is what an RCDD attaches to a bid
// or submits to the AHJ.
//
// Uses pdf-lib (pure JS, no native deps, Next.js-friendly). Production
// would also handle D-size 24"×36" sheet sets and revision clouds — for
// now we ship a clean Letter-sized package which is the more common
// submittal format anyway.

import type { Project } from "@/lib/projects/types";
import type { AuthUser } from "@/lib/auth/types";
import type { BomDocument } from "@/lib/bom/types";
import type { StandardsComplianceResult } from "@/lib/standards/types";
import type { RegulatoryReadinessReport } from "@/lib/regulatory/types";
import type { CableScheduleResult } from "@/lib/design/cable-schedule";

// ── Page geometry (US Letter, 1" margins) ──────────────────────────────
const PAGE_W = 612;   // 8.5" × 72
const PAGE_H = 792;   // 11"  × 72
const MARGIN = 54;    // 0.75"
const CONTENT_W = PAGE_W - MARGIN * 2;

const COLOR_BLACK    = { r: 0.10, g: 0.10, b: 0.10 };
const COLOR_DIM      = { r: 0.45, g: 0.45, b: 0.45 };
const COLOR_ACCENT   = { r: 0.96, g: 0.65, b: 0.14 };   // Revit amber
const COLOR_PASS     = { r: 0.25, g: 0.68, b: 0.36 };
const COLOR_WARN     = { r: 0.79, g: 0.58, b: 0.12 };
const COLOR_FAIL     = { r: 0.77, g: 0.29, b: 0.29 };

export interface GenerateSubmittalInput {
  project: Project;
  user?: Pick<AuthUser, "firstName" | "lastName" | "rcddNumber" | "rcddState" | "rcddExpiry" | "firmName" | "firmAddress" | "firmCity" | "firmState">;
  bom: BomDocument;
  compliance: StandardsComplianceResult;
  regulatory: RegulatoryReadinessReport;
  cableSchedule?: CableScheduleResult | null;
}

export async function generateSubmittalPdf(input: GenerateSubmittalInput): Promise<Uint8Array> {
  // Dynamic import — pdf-lib is optional. If it's not installed yet, throw a
  // clear error rather than a webpack ImportError.
  let pdflib: any;
  try {
    // @ts-expect-error — dynamic optional dependency
    pdflib = await import("pdf-lib");
  } catch {
    throw new Error("pdf-lib is not installed. Run `npm install` in frontend/ to enable submittal package generation.");
  }
  const { PDFDocument, StandardFonts, rgb } = pdflib;

  const pdf = await PDFDocument.create();
  const sans = await pdf.embedFont(StandardFonts.Helvetica);
  const sansBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const mono = await pdf.embedFont(StandardFonts.Courier);
  const monoBold = await pdf.embedFont(StandardFonts.CourierBold);

  // Shared layout helpers (closure over fonts)
  const ctx: Ctx = {
    pdf, sans, sansBold, mono, monoBold, rgb,
    page: null as any, y: 0, pageNum: 0,
    project: input.project, user: input.user,
  };

  newPage(ctx);
  drawCover(ctx, input);
  newPage(ctx);
  drawBom(ctx, input.bom);
  newPage(ctx);
  drawCompliance(ctx, input.compliance);
  newPage(ctx);
  drawRegulatory(ctx, input.regulatory);
  if (input.cableSchedule && input.cableSchedule.rows.length > 0) {
    newPage(ctx);
    drawCableSchedule(ctx, input.cableSchedule);
  }

  return pdf.save();
}

// ── Layout state ─────────────────────────────────────────────────────────

interface Ctx {
  pdf: any;
  sans: any; sansBold: any; mono: any; monoBold: any;
  rgb: (r: number, g: number, b: number) => any;
  page: any;
  y: number;
  pageNum: number;
  project: Project;
  user?: GenerateSubmittalInput["user"];
}

function newPage(ctx: Ctx) {
  ctx.page = ctx.pdf.addPage([PAGE_W, PAGE_H]);
  ctx.y = PAGE_H - MARGIN;
  ctx.pageNum += 1;
  // Project header strip (every page after cover)
  if (ctx.pageNum > 1) {
    drawHeader(ctx);
    drawFooter(ctx);
  }
}

function drawHeader(ctx: Ctx) {
  const y = PAGE_H - 32;
  ctx.page.drawText(`${ctx.project.number} · ${ctx.project.name}`, {
    x: MARGIN, y, size: 9, font: ctx.sansBold,
    color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
  });
  ctx.page.drawText("Submittal Package", {
    x: PAGE_W - MARGIN - 90, y, size: 9, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.page.drawLine({
    start: { x: MARGIN, y: y - 4 },
    end:   { x: PAGE_W - MARGIN, y: y - 4 },
    thickness: 0.5,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.y = y - 18;
}

function drawFooter(ctx: Ctx) {
  const y = 28;
  ctx.page.drawLine({
    start: { x: MARGIN, y: y + 12 }, end: { x: PAGE_W - MARGIN, y: y + 12 },
    thickness: 0.5, color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.page.drawText(`Generated by ToroAI · ${new Date().toLocaleDateString()}`, {
    x: MARGIN, y, size: 7, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.page.drawText(`Page ${ctx.pageNum}`, {
    x: PAGE_W - MARGIN - 36, y, size: 7, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
}

// ── Page renderers ───────────────────────────────────────────────────────

function drawCover(ctx: Ctx, input: GenerateSubmittalInput) {
  // Big accent band at the top
  ctx.page.drawRectangle({
    x: 0, y: PAGE_H - 12, width: PAGE_W, height: 12,
    color: ctx.rgb(COLOR_ACCENT.r, COLOR_ACCENT.g, COLOR_ACCENT.b),
  });

  let y = PAGE_H - 110;
  ctx.page.drawText("TOROAI", {
    x: MARGIN, y, size: 18, font: ctx.sansBold,
    color: ctx.rgb(COLOR_ACCENT.r, COLOR_ACCENT.g, COLOR_ACCENT.b),
  });
  y -= 20;
  ctx.page.drawText("SUBMITTAL PACKAGE", {
    x: MARGIN, y, size: 30, font: ctx.sansBold,
    color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
  });
  y -= 14;
  ctx.page.drawText("CSI Division 27 · Telecommunications Infrastructure", {
    x: MARGIN, y, size: 11, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });

  // Spacer
  y -= 50;
  ctx.page.drawLine({
    start: { x: MARGIN, y }, end: { x: PAGE_W - MARGIN, y },
    thickness: 0.75, color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
  });

  // Project info grid
  y -= 28;
  const rows: Array<[string, string]> = [
    ["PROJECT NUMBER", input.project.number],
    ["PROJECT NAME",   input.project.name],
    ["OWNER",          input.project.owner],
    ["SITE",           `${input.project.addressLine1}, ${input.project.city}, ${input.project.state} ${input.project.zip}`],
    ["AHJ",            input.project.ahj],
    ["BUILDING TYPE",  input.project.buildingType.replace(/_/g, " ").toUpperCase()],
    ["TOTAL SF",       input.project.totalSf.toLocaleString()],
    ["FLOORS",         String(input.project.floors)],
    ["TARGET OCCUPANCY", input.project.occupancyDate
      ? new Date(input.project.occupancyDate).toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
      : "—"],
  ];
  for (const [label, value] of rows) {
    ctx.page.drawText(label, { x: MARGIN, y, size: 8, font: ctx.sansBold,
      color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b) });
    ctx.page.drawText(value, { x: MARGIN + 130, y, size: 10, font: ctx.sans,
      color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b) });
    y -= 16;
  }

  // Exhibit callout (when present)
  if (input.project.exhibit) {
    y -= 12;
    ctx.page.drawRectangle({
      x: MARGIN, y: y - 76, width: CONTENT_W, height: 88,
      borderColor: ctx.rgb(COLOR_WARN.r, COLOR_WARN.g, COLOR_WARN.b),
      borderWidth: 0.75,
    });
    ctx.page.drawText("REDUCTION-TO-PRACTICE EXHIBIT — ToroAI TDD §7", {
      x: MARGIN + 8, y: y - 4, size: 8, font: ctx.sansBold,
      color: ctx.rgb(COLOR_WARN.r, COLOR_WARN.g, COLOR_WARN.b),
    });
    let ey = y - 22;
    const ex = input.project.exhibit;
    const exhibitLines = [
      `Cable: ${ex.cable.strandCount}-strand ${ex.cable.type.replace(/_/g, " ")} · ${ex.cable.totalLf} LF`,
      `From: ${ex.cable.startLocation}`,
      `To:   ${ex.cable.endLocation}`,
      `Connector: ${ex.cable.connectorSpec.replace("_", "/")} (mandatory per TDD §5.5)`,
      ex.davisBaconApplies ? "Davis-Bacon prevailing wage applies — labor rates pre-corrected." : "",
    ].filter(Boolean);
    for (const line of exhibitLines) {
      ctx.page.drawText(line, { x: MARGIN + 8, y: ey, size: 9, font: ctx.sans,
        color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b) });
      ey -= 12;
    }
    y -= 92;
  }

  // RCDD / PE stamp box
  y -= 8;
  const stampW = 250;
  const stampH = 110;
  const stampY = y - stampH;
  ctx.page.drawRectangle({
    x: MARGIN, y: stampY, width: stampW, height: stampH,
    borderColor: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
    borderWidth: 1,
  });
  ctx.page.drawText("RCDD / PE STAMP", { x: MARGIN + 8, y: y - 14, size: 9, font: ctx.sansBold,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b) });
  if (input.user) {
    const fullName = `${input.user.firstName} ${input.user.lastName}`.toUpperCase();
    ctx.page.drawText(fullName, { x: MARGIN + 8, y: y - 32, size: 11, font: ctx.sansBold,
      color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b) });
    if (input.user.rcddNumber) {
      ctx.page.drawText(`RCDD #${input.user.rcddNumber}  (${input.user.rcddState ?? "—"})`, {
        x: MARGIN + 8, y: y - 48, size: 9, font: ctx.sans,
        color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
      });
    }
    if (input.user.rcddExpiry) {
      ctx.page.drawText(`Expires ${new Date(input.user.rcddExpiry).toLocaleDateString()}`, {
        x: MARGIN + 8, y: y - 62, size: 8, font: ctx.sans,
        color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
      });
    }
    if (input.user.firmName) {
      ctx.page.drawText(input.user.firmName, { x: MARGIN + 8, y: y - 82, size: 9, font: ctx.sans,
        color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b) });
    }
  }
  // Signature line
  ctx.page.drawLine({
    start: { x: MARGIN + 8, y: stampY + 18 }, end: { x: MARGIN + stampW - 8, y: stampY + 18 },
    thickness: 0.5, color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.page.drawText("Signature / Date", { x: MARGIN + 8, y: stampY + 6, size: 7, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b) });

  // Footer
  ctx.page.drawText(`Generated ${new Date().toLocaleString()} by ToroAI`, {
    x: MARGIN, y: 36, size: 8, font: ctx.sans,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
}

function drawBom(ctx: Ctx, bom: BomDocument) {
  drawSectionTitle(ctx, "Bill of Materials");
  drawText(ctx, `CSI Division 27 · ${bom.lineItems.length} line items`, { size: 9, color: COLOR_DIM });
  ctx.y -= 10;

  // Section subtotals
  drawText(ctx, "SECTION TOTALS", { size: 8, font: "bold", color: COLOR_DIM });
  ctx.y -= 4;
  for (const sec of bom.sections) {
    drawRow(ctx, [
      { text: sec.section, width: CONTENT_W - 90 - 60 - 8, size: 9 },
      { text: `${sec.itemCount} items`, width: 60, size: 9, align: "right", color: COLOR_DIM },
      { text: dollars(sec.subtotalCents), width: 90, size: 9, align: "right", font: "mono" },
    ]);
  }
  ctx.y -= 14;

  // Line items
  for (const sec of bom.sections) {
    const items = bom.lineItems.filter(l => l.csiSection === sec.section);
    if (items.length === 0) continue;
    ensureRoom(ctx, 30);
    drawText(ctx, sec.section, { size: 9, font: "bold" });
    ctx.y -= 4;
    drawDividerLine(ctx);
    // Column header
    drawRow(ctx, [
      { text: "#",   width: 18, size: 7, color: COLOR_DIM, font: "bold" },
      { text: "MFR · SKU",  width: 130, size: 7, color: COLOR_DIM, font: "bold" },
      { text: "Description", width: CONTENT_W - 18 - 130 - 36 - 48 - 70, size: 7, color: COLOR_DIM, font: "bold" },
      { text: "Qty", width: 36, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
      { text: "Unit", width: 28, size: 7, color: COLOR_DIM, font: "bold" },
      { text: "Extended", width: 70, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
    ]);
    for (const line of items) {
      ensureRoom(ctx, 22);
      drawRow(ctx, [
        { text: String(line.lineNo), width: 18, size: 7, color: COLOR_DIM },
        { text: line.manufacturer + "\n" + line.sku, width: 130, size: 7 },
        { text: line.description, width: CONTENT_W - 18 - 130 - 36 - 48 - 70, size: 7 },
        { text: String(line.quantity), width: 36, size: 7, align: "right", font: "mono" },
        { text: line.unit, width: 28, size: 7 },
        { text: dollars(line.extendedCents), width: 70, size: 7, align: "right", font: "mono" },
      ]);
    }
    ctx.y -= 4;
    // Subtotal
    drawRow(ctx, [
      { text: "", width: CONTENT_W - 90 - 8 },
      { text: `Subtotal · ${dollars(sec.subtotalCents)}`, width: 90, size: 9,
        align: "right", font: "bold", color: COLOR_ACCENT },
    ]);
    ctx.y -= 12;
  }

  // Totals box
  ensureRoom(ctx, 90);
  ctx.y -= 6;
  drawDividerLine(ctx);
  ctx.y -= 12;
  const totalsRows: Array<[string, string]> = [
    ["Material subtotal",  dollars(bom.materialSubtotalCents)],
    [`Labor · ${bom.labor.hours.toFixed(1)} hr @ $${(bom.labor.blendedRateCentsPerHr/100).toFixed(2)}/hr`,
                           dollars(bom.labor.subtotalCents)],
    [`Tax · ${(bom.tax.rate * 100).toFixed(2)}%`,
                           dollars(bom.tax.cents)],
  ];
  for (const [k, v] of totalsRows) {
    drawRow(ctx, [
      { text: k, width: CONTENT_W - 100 - 8, size: 9, align: "right" },
      { text: v, width: 100, size: 9, align: "right", font: "mono" },
    ]);
  }
  ctx.y -= 6;
  drawRow(ctx, [
    { text: "GRAND TOTAL", width: CONTENT_W - 110 - 8, size: 11, align: "right", font: "bold" },
    { text: dollars(bom.grandTotalCents), width: 110, size: 12, align: "right",
      font: "bold", color: COLOR_ACCENT },
  ]);
}

function drawCompliance(ctx: Ctx, c: StandardsComplianceResult) {
  drawSectionTitle(ctx, "Compliance Report");
  drawText(ctx, "20-rule corpus · BICSI TDMM 15 · TIA-568/569/758/607 · NEC 770/800 · UFC 3-580-01", {
    size: 9, color: COLOR_DIM,
  });
  ctx.y -= 12;

  // Summary tiles
  const counts = c.counts;
  drawTile(ctx, 0, "Pass", String(counts.pass), COLOR_PASS);
  drawTile(ctx, 1, "Advisory", String(counts.advisory), COLOR_WARN);
  drawTile(ctx, 2, "Fail", String(counts.fail), COLOR_FAIL);
  drawTile(ctx, 3, "N/A", String(counts.not_applicable), COLOR_DIM);
  ctx.y -= 60;

  // Per-rule table
  drawDividerLine(ctx);
  drawRow(ctx, [
    { text: "Code",      width: 130, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Rule",      width: CONTENT_W - 130 - 60 - 8, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Status",    width: 60, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
  ]);
  for (const { def, outcome } of c.rules) {
    ensureRoom(ctx, 22);
    const statusColor =
      outcome.status === "pass" ? COLOR_PASS
      : outcome.status === "fail" ? COLOR_FAIL
      : outcome.status === "advisory" ? COLOR_WARN
      : COLOR_DIM;
    drawRow(ctx, [
      { text: def.code, width: 130, size: 7, font: "mono", color: COLOR_DIM },
      { text: def.title, width: CONTENT_W - 130 - 60 - 8, size: 8 },
      { text: outcome.status.toUpperCase(), width: 60, size: 7, font: "bold",
        align: "right", color: statusColor },
    ]);
    if (outcome.message) {
      drawText(ctx, "    " + outcome.message, { size: 7, color: COLOR_DIM });
    }
  }
}

function drawRegulatory(ctx: Ctx, r: RegulatoryReadinessReport) {
  drawSectionTitle(ctx, "Regulatory Readiness");
  drawText(ctx, `${r.permitRequirements.length} permits · ${r.environmentalFlags.length} environmental flags · longest lead ${r.longestPermitLeadDays} days`, {
    size: 9, color: COLOR_DIM,
  });
  ctx.y -= 12;

  // Jurisdiction stack
  drawText(ctx, "JURISDICTIONAL STACK", { size: 8, font: "bold", color: COLOR_DIM });
  ctx.y -= 4;
  for (const j of [
    { l: "City",     v: r.jurisdictionStack.city.name },
    { l: "County",   v: r.jurisdictionStack.county.name },
    { l: "State",    v: r.jurisdictionStack.state.name },
    { l: "Federal",  v: r.jurisdictionStack.federal.name },
    { l: "State DOT", v: `${r.jurisdictionStack.dot.acronym} — ${r.jurisdictionStack.dot.name}` },
  ]) {
    drawRow(ctx, [
      { text: j.l, width: 80, size: 9, color: COLOR_DIM },
      { text: j.v, width: CONTENT_W - 80, size: 9 },
    ]);
  }
  ctx.y -= 14;

  // Permits
  drawText(ctx, "REQUIRED PERMITS", { size: 8, font: "bold", color: COLOR_DIM });
  ctx.y -= 4;
  drawDividerLine(ctx);
  drawRow(ctx, [
    { text: "Permit", width: CONTENT_W - 60 - 80 - 16, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Lead",   width: 60, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
    { text: "Fee",    width: 80, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
  ]);
  for (const p of r.permitRequirements) {
    ensureRoom(ctx, 26);
    drawRow(ctx, [
      { text: p.definition.label, width: CONTENT_W - 60 - 80 - 16, size: 8 },
      { text: `${p.leadTimeDays} d`, width: 60, size: 8, align: "right", font: "mono" },
      { text: dollars(p.estimatedFeeCents), width: 80, size: 8, align: "right", font: "mono" },
    ]);
    drawText(ctx, "    " + p.authority.name + (p.authority.unit ? " — " + p.authority.unit : ""), {
      size: 7, color: COLOR_DIM,
    });
  }
  ctx.y -= 10;

  // Environmental flags
  if (r.environmentalFlags.length > 0) {
    drawText(ctx, "ENVIRONMENTAL FLAGS", { size: 8, font: "bold", color: COLOR_DIM });
    ctx.y -= 4;
    for (const f of r.environmentalFlags) {
      ensureRoom(ctx, 20);
      const color = f.blocksConstruction ? COLOR_FAIL : COLOR_WARN;
      drawText(ctx, "▸ " + f.kind.replace(/_/g, " ").toUpperCase() +
        (f.blocksConstruction ? " — BLOCKS CONSTRUCTION START" : ""), {
          size: 9, font: "bold", color,
      });
      drawText(ctx, "    " + f.rationale, { size: 8, color: COLOR_BLACK });
    }
  }
}

function drawCableSchedule(ctx: Ctx, s: CableScheduleResult) {
  drawSectionTitle(ctx, "Cable Run Schedule");
  drawText(ctx, `${s.rows.length} runs · ${s.totalCableLf.toLocaleString()} LF total · TIA-606-C labels`, {
    size: 9, color: COLOR_DIM,
  });
  ctx.y -= 12;
  drawDividerLine(ctx);
  drawRow(ctx, [
    { text: "Label",      width: 70, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Source",     width: 110, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Destination", width: CONTENT_W - 70 - 110 - 60 - 50, size: 7, color: COLOR_DIM, font: "bold" },
    { text: "Length",     width: 60, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
    { text: "Status",     width: 50, size: 7, color: COLOR_DIM, font: "bold", align: "right" },
  ]);
  for (const r of s.rows) {
    ensureRoom(ctx, 16);
    const statusColor = r.status === "fail" ? COLOR_FAIL : r.status === "warn" ? COLOR_WARN : COLOR_PASS;
    drawRow(ctx, [
      { text: r.label, width: 70, size: 7, font: "mono" },
      { text: r.sourceTrLabel + " · " + r.sourcePort, width: 110, size: 7, font: "mono", color: COLOR_DIM },
      { text: r.destRoomName + " (F" + r.destFloor + ")", width: CONTENT_W - 70 - 110 - 60 - 50, size: 7 },
      { text: r.lengthFt + " ft", width: 60, size: 7, align: "right", font: "mono" },
      { text: r.status.toUpperCase(), width: 50, size: 7, align: "right", font: "bold", color: statusColor },
    ]);
  }
}

// ── Layout primitives ───────────────────────────────────────────────────

function drawSectionTitle(ctx: Ctx, title: string) {
  ctx.page.drawText(title, {
    x: MARGIN, y: ctx.y, size: 18, font: ctx.sansBold,
    color: ctx.rgb(COLOR_BLACK.r, COLOR_BLACK.g, COLOR_BLACK.b),
  });
  ctx.page.drawRectangle({
    x: MARGIN, y: ctx.y - 6, width: 40, height: 2.5,
    color: ctx.rgb(COLOR_ACCENT.r, COLOR_ACCENT.g, COLOR_ACCENT.b),
  });
  ctx.y -= 22;
}

interface Cell {
  text: string;
  width: number;
  size?: number;
  font?: "regular" | "bold" | "mono";
  color?: { r: number; g: number; b: number };
  align?: "left" | "right";
}

function drawRow(ctx: Ctx, cells: Cell[]) {
  // Determine row height by tallest cell
  let maxLines = 1;
  const wrappedPerCell: string[][] = cells.map(c => {
    const lines = c.text.split("\n").flatMap(line => wrapText(line, c.width - 4, c.size ?? 9, c.font ?? "regular"));
    if (lines.length > maxLines) maxLines = lines.length;
    return lines;
  });
  const lineHeight = 10;
  let x = MARGIN;
  for (let i = 0; i < cells.length; i++) {
    const c = cells[i];
    const lines = wrappedPerCell[i];
    const fontObj = c.font === "bold" ? ctx.sansBold
      : c.font === "mono" ? (c.font === "mono" ? ctx.mono : ctx.sans)
      : ctx.sans;
    const sz = c.size ?? 9;
    const color = c.color ?? COLOR_BLACK;
    for (let li = 0; li < lines.length; li++) {
      const text = lines[li];
      const tw = textWidth(text, sz, c.font ?? "regular");
      const cx = c.align === "right" ? x + c.width - tw - 2 : x + 2;
      const cy = ctx.y - li * lineHeight;
      ctx.page.drawText(text, { x: cx, y: cy, size: sz, font: fontObj,
        color: ctx.rgb(color.r, color.g, color.b) });
    }
    x += c.width;
  }
  ctx.y -= lineHeight * maxLines + 2;
}

function drawText(ctx: Ctx, text: string, opts?: { size?: number; font?: "regular" | "bold" | "mono"; color?: { r: number; g: number; b: number } }) {
  const sz = opts?.size ?? 10;
  const fontObj = opts?.font === "bold" ? ctx.sansBold
    : opts?.font === "mono" ? ctx.mono
    : ctx.sans;
  const color = opts?.color ?? COLOR_BLACK;
  const lines = wrapText(text, CONTENT_W, sz, opts?.font ?? "regular");
  for (const line of lines) {
    ensureRoom(ctx, sz + 4);
    ctx.page.drawText(line, { x: MARGIN, y: ctx.y, size: sz, font: fontObj,
      color: ctx.rgb(color.r, color.g, color.b) });
    ctx.y -= sz + 2;
  }
}

function drawDividerLine(ctx: Ctx) {
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.y + 2 },
    end:   { x: PAGE_W - MARGIN, y: ctx.y + 2 },
    thickness: 0.5,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b),
  });
  ctx.y -= 6;
}

function drawTile(ctx: Ctx, idx: number, label: string, value: string, color: typeof COLOR_PASS) {
  const tileW = (CONTENT_W - 12) / 4;
  const x = MARGIN + idx * (tileW + 4);
  const top = ctx.y;
  ctx.page.drawRectangle({
    x, y: top - 50, width: tileW, height: 50,
    borderColor: ctx.rgb(color.r, color.g, color.b), borderWidth: 0.75,
  });
  ctx.page.drawText(label, { x: x + 6, y: top - 14, size: 7, font: ctx.sansBold,
    color: ctx.rgb(COLOR_DIM.r, COLOR_DIM.g, COLOR_DIM.b) });
  ctx.page.drawText(value, { x: x + 6, y: top - 36, size: 18, font: ctx.sansBold,
    color: ctx.rgb(color.r, color.g, color.b) });
}

function ensureRoom(ctx: Ctx, needed: number) {
  if (ctx.y - needed < MARGIN + 30) {
    newPage(ctx);
  }
}

// ── Text width + wrapping ───────────────────────────────────────────────

const AVG_WIDTHS = { regular: 0.5, bold: 0.55, mono: 0.6 };

function textWidth(text: string, size: number, font: "regular" | "bold" | "mono"): number {
  // Helvetica + Courier are roughly 0.5/0.6 × size per char
  return text.length * AVG_WIDTHS[font] * size;
}

function wrapText(text: string, maxWidth: number, size: number, font: "regular" | "bold" | "mono"): string[] {
  if (textWidth(text, size, font) <= maxWidth) return [text];
  const words = text.split(/\s+/);
  const lines: string[] = [];
  let current = "";
  for (const word of words) {
    const tentative = current ? current + " " + word : word;
    if (textWidth(tentative, size, font) <= maxWidth) {
      current = tentative;
    } else {
      if (current) lines.push(current);
      current = word;
    }
  }
  if (current) lines.push(current);
  return lines;
}

// ── Helpers ─────────────────────────────────────────────────────────────

function dollars(cents: number): string {
  return "$" + (cents / 100).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}
